# -*- coding: utf-8 -*-
from abc import ABC, abstractmethod

class RepositoryInterface(ABC):
    @abstractmethod
    def create(self, obj): ...
    @abstractmethod
    def get_all(self): ...
    @abstractmethod
    def get_by_id(self, id): ...
    @abstractmethod
    def update(self, id, data): ...
    @abstractmethod
    def delete(self, id): ...